// <auto-generated />
using LiquourStore.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiquorStore.DAL.Migrations
{
    [DbContext(typeof(LiquorStoreContext))]
    [Migration("20200428070721_AddLiquorType")]
    partial class AddLiquorType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LiquorStore.DAL.Entities.DatabaseEntities.Liquor", b =>
                {
                    b.Property<int>("LiquorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LiquorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiquorTypeId")
                        .HasColumnType("int");

                    b.HasKey("LiquorId");

                    b.HasIndex("LiquorTypeId");

                    b.ToTable("Liquors");
                });

            modelBuilder.Entity("LiquorStore.DAL.Entities.DatabaseEntities.LiquorType", b =>
                {
                    b.Property<int>("LiquorTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LiquorTypeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("LiquorTypeId");

                    b.ToTable("LiquorType");
                });

            modelBuilder.Entity("LiquorStore.DAL.Entities.DatabaseEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiquorStore.DAL.Entities.DatabaseEntities.Liquor", b =>
                {
                    b.HasOne("LiquorStore.DAL.Entities.DatabaseEntities.LiquorType", "LiquorType")
                        .WithMany()
                        .HasForeignKey("LiquorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
